# .github/workflows/build.yml
name: Build Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Clone and Bootstrap vcpkg
        if: runner.os == 'Windows'
        run: git clone --depth 1 https://github.com/microsoft/vcpkg.git && .\vcpkg\bootstrap-vcpkg.bat
        shell: cmd
      

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.2

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse
